Initial implementation
charmed-kubernetes/interface-aws-iam pull request #1
Opened 2019-07-25 20:53 UTC by hyperbolic2346

2019-08-26 15:47 UTC, johnsca commented on provides.py
> +    @when('endpoint.{endpoint_name}.changed')
This potentially has the same bug as the CNI interface which could leave it stuck with the flags unset: https://github.com/juju-solutions/interface-kubernetes-cni/pull/5

However, now that charms.reactive 1.3.0 is out, I think that defining a [`manage_flags` method](https://discourse.jujucharms.com/t/new-option-for-managing-flags-in-endpoints/1987) would be a cleaner solution.

2019-08-27 13:45 UTC, hyperbolic2346 commented on provides.py
> +    @when('endpoint.{endpoint_name}.changed')
thank you for catching this. I've updated this interface to use manage_flags and the code size shrunk considerably and the readability went up. :cake:

2019-08-27 14:48 UTC, hyperbolic2346 commented
https://bugs.launchpad.net/charm-kubernetes-master/+bug/1841439

2019-08-29 15:56 UTC, tvansteenburgh reviewed
Please add some depth to the readme. See https://github.com/charmed-kubernetes/interface-openstack-integration and https://github.com/charmed-kubernetes/interface-kube-control for good examples.

2019-08-29 16:03 UTC, johnsca approved these changes
LGTM

2019-08-29 16:03 UTC, johnsca commented on provides.py
> +            return None
This is fine as is, but for reference it is functionally equivalent to:

```python
def get_cluster_id(self):
    return self.all_joined_units.received['cluster_id']
```

2019-08-29 17:44 UTC, hyperbolic2346 commented on provides.py
> +            return None
I like this much better. I have changed it to that. I was worried that if all_joined_units was None that it would explode. Maybe it's just my C background haunting me.

2019-08-29 18:13 UTC, johnsca approved these changes

2019-08-29 19:10 UTC, tvansteenburgh requested changes

2019-08-29 19:10 UTC, tvansteenburgh commented on README.md
> + * `set_api_server_status`
What does this do?

2019-08-29 19:10 UTC, tvansteenburgh commented on provides.py
> +    def set_api_server_status(self, status):
What are the possible values of `status` here? Please include in a doc string.

2019-08-29 19:10 UTC, tvansteenburgh commented on requires.py
> +    def set_webhook_status(self, status):
What are the possible values of `status` here? Please include in a doc string.

2019-08-29 19:10 UTC, tvansteenburgh commented on README.md
> +and aws-iam subordinate
Would be nice to link to the kubernetes-master and aws-iam repos here. Also add period at end of sentence.

2019-08-29 19:10 UTC, tvansteenburgh commented on README.md
> +   Indicates that there are one or more charms on the other side of the relation
s/charms/units/

2019-08-29 19:10 UTC, tvansteenburgh commented on README.md
> +   in the kubectl configuration file. This is passed over the relation here.
s/passed over/retrieved from/

2019-08-29 19:10 UTC, tvansteenburgh commented on README.md
> +   Indicates that there are one or more charms on the other side of the relation
s/charms/units/

2019-08-30 12:17 UTC, hyperbolic2346 commented
Thanks for the thorough reviews.

2019-08-30 16:10 UTC, tvansteenburgh approved these changes

2019-08-30 16:10 UTC, merged